services:
  web:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "8004:8000"
    env_file:
      - backend/.env
    volumes:
      - ${EC2_DATA_DIR}/db.sqlite3:/app/backend/db.sqlite3
      - ${EC2_DATA_DIR}/media:/app/backend/media
      - staticfiles:/app/backend/staticfiles
    restart: unless-stopped

volumes:
  staticfiles:
